"""
Strategy engine — signal generation with strict confluence filtering.
Institutional-style entry/exit logic with advanced filters.
"""

from dataclasses import dataclass
from enum import Enum
from typing import Optional

import pandas as pd
import numpy as np

from config import settings
from utils.logger import get_logger

log = get_logger("strategy")


class Side(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"


@dataclass
class Signal:
    """Trade signal generated by the strategy."""
    side: Side
    pair: str
    entry_price: float
    stop_loss: float
    take_profit: float
    atr: float
    confidence: float  # 0-1, based on confluence count


@dataclass
class Position:
    """Active position tracking."""
    pair: str
    side: Side
    entry_price: float
    quantity: float
    stop_loss: float
    take_profit: float
    trail_active: bool = False
    trail_stop: float = 0.0
    entry_time: str = ""
    highest_price: float = 0.0  # For long trailing
    lowest_price: float = float("inf")  # For short trailing


class StrategyEngine:
    """Generates trade signals from indicator-enriched DataFrames."""

    def __init__(self):
        self.positions: dict[str, Position] = {}  # pair -> Position
        self._last_trade_bar: dict[str, int] = {}  # pair -> bar index
        self._current_bar: int = 0

    def evaluate(self, pair: str, df: pd.DataFrame) -> Optional[Signal]:
        """Evaluate latest bar for entry signal.
        
        Args:
            pair: Trading pair symbol
            df: DataFrame with indicators computed (from indicators.compute_all)
        
        Returns:
            Signal if conditions met, None otherwise
        """
        if len(df) < settings.EMA_TREND + 5:
            return None

        self._current_bar += 1
        row = df.iloc[-1]

        # Skip if already in a position for this pair
        if pair in self.positions:
            return None

        # Cooldown: skip if too soon after last trade
        last = self._last_trade_bar.get(pair, -999)
        if self._current_bar - last < settings.TRADE_COOLDOWN_BARS:
            return None

        # ── Advanced Filters ──
        # Low volatility filter
        if row["atr_pct"] < settings.ATR_MIN_THRESHOLD:
            return None

        # S/R proximity filter
        close = row["close"]
        if pd.notna(row["resistance"]) and pd.notna(row["support"]):
            r_dist = abs(close - row["resistance"]) / close
            s_dist = abs(close - row["support"]) / close
            if r_dist < settings.SR_PROXIMITY_PCT or s_dist < settings.SR_PROXIMITY_PCT:
                return None

        # ── Check Long Setup ──
        long_signal = self._check_long(df, pair)
        if long_signal:
            return long_signal

        # ── Check Short Setup ──
        short_signal = self._check_short(df, pair)
        if short_signal:
            return short_signal

        return None

    def _check_long(self, df: pd.DataFrame, pair: str) -> Optional[Signal]:
        """Check long entry conditions with lookback window for crossovers."""
        row = df.iloc[-1]
        lookback = df.iloc[-5:]  # Last 5 bars for crossover detection

        conditions = []

        # 1. Price above VWAP
        conditions.append(row["close"] > row["vwap"])

        # 2. EMA 9 above EMA 21 (bullish alignment) OR crossed within last 5 bars
        ema_bullish = row["ema_fast"] > row["ema_slow"]
        ema_spread = (row["ema_fast"] - row["ema_slow"]) / row["close"]
        ema_crossed_recent = lookback["ema_cross_up"].any()
        conditions.append((ema_bullish and ema_spread > settings.EMA_SPREAD_MIN) or ema_crossed_recent)

        # 3. Price above EMA 200
        conditions.append(row["close"] > row["ema_trend"])

        # 4. RSI between 40-70 (momentum without being overbought)
        rsi_ok = 40 < row["rsi"] < 70
        rsi_crossed_recent = lookback["rsi_cross_40_up"].any()
        conditions.append(rsi_ok or rsi_crossed_recent)

        # 5. Volume spike (current bar or within last 3 bars)
        vol_spike = lookback.tail(3)["vol_spike"].any()
        conditions.append(vol_spike)

        # Optional MACD confirmation
        if settings.USE_MACD_FILTER:
            conditions.append(row["macd_hist"] > 0)

        met = sum(conditions)
        total = len(conditions)

        # Require 4 out of 5 core conditions (high confluence)
        min_required = total - 1
        if met < min_required:
            return None

        close = row["close"]
        atr = row["atr"]

        # Dynamic SL/TP based on ATR
        sl_distance = max(settings.SL_MIN, min(settings.SL_MAX, atr / close))
        tp_distance = max(settings.TP_MIN, min(settings.TP_MAX, (atr / close) * 3))

        stop_loss = close * (1 - sl_distance)
        take_profit = close * (1 + tp_distance)

        # Enforce minimum R:R of 1.5:1
        reward = tp_distance
        risk = sl_distance
        if risk > 0 and reward / risk < 1.5:
            return None

        log.signal(
            f"LONG signal: {pair} @ {close:.2f} | SL: {stop_loss:.2f} | TP: {take_profit:.2f}"
        )

        return Signal(
            side=Side.LONG,
            pair=pair,
            entry_price=close,
            stop_loss=stop_loss,
            take_profit=take_profit,
            atr=atr,
            confidence=met / total,
        )

    def _check_short(self, df: pd.DataFrame, pair: str) -> Optional[Signal]:
        """Check short entry conditions with lookback window."""
        row = df.iloc[-1]
        lookback = df.iloc[-5:]

        conditions = []

        # 1. Price below VWAP
        conditions.append(row["close"] < row["vwap"])

        # 2. EMA 9 below EMA 21 (bearish alignment) OR crossed within last 5 bars
        ema_bearish = row["ema_fast"] < row["ema_slow"]
        ema_spread = (row["ema_slow"] - row["ema_fast"]) / row["close"]
        ema_crossed_recent = lookback["ema_cross_down"].any()
        conditions.append((ema_bearish and ema_spread > settings.EMA_SPREAD_MIN) or ema_crossed_recent)

        # 3. Price below EMA 200
        conditions.append(row["close"] < row["ema_trend"])

        # 4. RSI between 30-60 (momentum without being oversold)
        rsi_ok = 30 < row["rsi"] < 60
        rsi_crossed_recent = lookback["rsi_cross_60_down"].any()
        conditions.append(rsi_ok or rsi_crossed_recent)

        # 5. Volume spike
        vol_spike = lookback.tail(3)["vol_spike"].any()
        conditions.append(vol_spike)

        if settings.USE_MACD_FILTER:
            conditions.append(row["macd_hist"] < 0)

        met = sum(conditions)
        total = len(conditions)

        min_required = total - 1
        if met < min_required:
            return None

        close = row["close"]
        atr = row["atr"]

        sl_distance = max(settings.SL_MIN, min(settings.SL_MAX, atr / close))
        tp_distance = max(settings.TP_MIN, min(settings.TP_MAX, (atr / close) * 3))

        stop_loss = close * (1 + sl_distance)
        take_profit = close * (1 - tp_distance)

        # Enforce minimum R:R of 1.5:1
        reward = tp_distance
        risk = sl_distance
        if risk > 0 and reward / risk < 1.5:
            return None

        log.signal(
            f"SHORT signal: {pair} @ {close:.2f} | SL: {stop_loss:.2f} | TP: {take_profit:.2f}"
        )

        return Signal(
            side=Side.SHORT,
            pair=pair,
            entry_price=close,
            stop_loss=stop_loss,
            take_profit=take_profit,
            atr=atr,
            confidence=met / total,
        )

    def check_exit(self, pair: str, current_price: float) -> Optional[str]:
        """Check if active position should be closed.
        
        Returns:
            Exit reason string or None
        """
        if pair not in self.positions:
            return None

        pos = self.positions[pair]

        if pos.side == Side.LONG:
            return self._check_long_exit(pos, current_price)
        else:
            return self._check_short_exit(pos, current_price)

    def _check_long_exit(self, pos: Position, price: float) -> Optional[str]:
        """Check long position exit conditions."""
        # Stop loss hit
        if price <= pos.stop_loss:
            return "SL"

        # Take profit hit
        if price >= pos.take_profit:
            return "TP"

        # Trailing stop logic
        if price > pos.highest_price:
            pos.highest_price = price

        # Activate trailing stop at +0.2%
        profit_pct = (price - pos.entry_price) / pos.entry_price
        if profit_pct >= settings.TRAIL_ACTIVATE:
            pos.trail_active = True
            new_trail = price * (1 - settings.TRAIL_DISTANCE)
            pos.trail_stop = max(pos.trail_stop, new_trail)

        if pos.trail_active and price <= pos.trail_stop:
            return "TRAIL"

        return None

    def _check_short_exit(self, pos: Position, price: float) -> Optional[str]:
        """Check short position exit conditions."""
        if price >= pos.stop_loss:
            return "SL"

        if price <= pos.take_profit:
            return "TP"

        if price < pos.lowest_price:
            pos.lowest_price = price

        profit_pct = (pos.entry_price - price) / pos.entry_price
        if profit_pct >= settings.TRAIL_ACTIVATE:
            pos.trail_active = True
            new_trail = price * (1 + settings.TRAIL_DISTANCE)
            pos.trail_stop = min(pos.trail_stop, new_trail) if pos.trail_stop > 0 else new_trail

        if pos.trail_active and price >= pos.trail_stop:
            return "TRAIL"

        return None

    def open_position(self, pair: str, signal: Signal, quantity: float,
                      entry_time: str = ""):
        """Register a new position."""
        pos = Position(
            pair=pair,
            side=signal.side,
            entry_price=signal.entry_price,
            quantity=quantity,
            stop_loss=signal.stop_loss,
            take_profit=signal.take_profit,
            entry_time=entry_time,
            highest_price=signal.entry_price,
            lowest_price=signal.entry_price,
        )
        self.positions[pair] = pos
        log.trade(f"OPENED {signal.side.value} {pair} | qty={quantity:.6f} @ {signal.entry_price:.2f}")

    def close_position(self, pair: str) -> Optional[Position]:
        """Remove and return closed position."""
        self._last_trade_bar[pair] = self._current_bar
        return self.positions.pop(pair, None)

    @property
    def open_position_count(self) -> int:
        return len(self.positions)
